# DataSource Config
spring:
  profiles:
    active: dev
  application:
    name: wow-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://67.207.80.139:3306/wow-payment?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456a
swagger:
  enable: true
  application-version: 1.0
  application-description: Swagger 3.0 for WOW backend
  try-host: http://localhost:${server.port}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
